// Package testutil offers test utility for parser
package testutil

import (
	"go/token"

	"github.com/go-generalize/go-easyparser/testutil"
)

// ParsePositionString parses position notations generated by token.Position.String()
func ParsePositionString(s string) *token.Position {
	return testutil.ParsePositionString(s)
}
